# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGridLayout,
    QGroupBox, QHBoxLayout, QLabel, QLineEdit,
    QMainWindow, QProgressBar, QPushButton, QRadioButton,
    QScrollBar, QSizePolicy, QTabWidget, QTextEdit,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 668)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(0, 0, 798, 561))
        self.tabWidget.setMinimumSize(QSize(791, 0))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.tabWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.tab_inicio = QWidget()
        self.tab_inicio.setObjectName(u"tab_inicio")
        self.tabWidget.addTab(self.tab_inicio, "")
        self.tab_renpy = QWidget()
        self.tab_renpy.setObjectName(u"tab_renpy")
        self.frame_title_renpy = QFrame(self.tab_renpy)
        self.frame_title_renpy.setObjectName(u"frame_title_renpy")
        self.frame_title_renpy.setGeometry(QRect(10, 10, 761, 50))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_title_renpy.sizePolicy().hasHeightForWidth())
        self.frame_title_renpy.setSizePolicy(sizePolicy)
        self.frame_title_renpy.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_title_renpy.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame_title_renpy)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.lbl_title = QLabel(self.frame_title_renpy)
        self.lbl_title.setObjectName(u"lbl_title")
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(20)
        self.lbl_title.setFont(font1)
        self.lbl_title.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lbl_title.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.lbl_title)

        self.groupBox_actions_renpy = QGroupBox(self.tab_renpy)
        self.groupBox_actions_renpy.setObjectName(u"groupBox_actions_renpy")
        self.groupBox_actions_renpy.setGeometry(QRect(20, 280, 732, 100))
        self.gridLayout = QGridLayout(self.groupBox_actions_renpy)
        self.gridLayout.setObjectName(u"gridLayout")
        self.chk_rpa_renpy = QCheckBox(self.groupBox_actions_renpy)
        self.chk_rpa_renpy.setObjectName(u"chk_rpa_renpy")

        self.gridLayout.addWidget(self.chk_rpa_renpy, 0, 0, 1, 1)

        self.chk_sources_renpy = QCheckBox(self.groupBox_actions_renpy)
        self.chk_sources_renpy.setObjectName(u"chk_sources_renpy")

        self.gridLayout.addWidget(self.chk_sources_renpy, 0, 2, 1, 1)

        self.chk_music_renpy = QCheckBox(self.groupBox_actions_renpy)
        self.chk_music_renpy.setObjectName(u"chk_music_renpy")

        self.gridLayout.addWidget(self.chk_music_renpy, 1, 1, 1, 1)

        self.chk_all_renpy = QCheckBox(self.groupBox_actions_renpy)
        self.chk_all_renpy.setObjectName(u"chk_all_renpy")

        self.gridLayout.addWidget(self.chk_all_renpy, 0, 3, 1, 1)

        self.chk_rpyc_renpy = QCheckBox(self.groupBox_actions_renpy)
        self.chk_rpyc_renpy.setObjectName(u"chk_rpyc_renpy")

        self.gridLayout.addWidget(self.chk_rpyc_renpy, 1, 0, 1, 1)

        self.chk_video_renpy = QCheckBox(self.groupBox_actions_renpy)
        self.chk_video_renpy.setObjectName(u"chk_video_renpy")

        self.gridLayout.addWidget(self.chk_video_renpy, 1, 2, 1, 1)

        self.chk_img_renpy = QCheckBox(self.groupBox_actions_renpy)
        self.chk_img_renpy.setObjectName(u"chk_img_renpy")

        self.gridLayout.addWidget(self.chk_img_renpy, 0, 1, 1, 1)

        self.btn_inicio_renpy = QPushButton(self.tab_renpy)
        self.btn_inicio_renpy.setObjectName(u"btn_inicio_renpy")
        self.btn_inicio_renpy.setGeometry(QRect(20, 460, 734, 61))
        font2 = QFont()
        font2.setFamilies([u"Arial"])
        font2.setPointSize(26)
        self.btn_inicio_renpy.setFont(font2)
        self.widget_dirs_renpy = QWidget(self.tab_renpy)
        self.widget_dirs_renpy.setObjectName(u"widget_dirs_renpy")
        self.widget_dirs_renpy.setGeometry(QRect(10, 80, 759, 114))
        self.it_origen_renpy = QLineEdit(self.widget_dirs_renpy)
        self.it_origen_renpy.setObjectName(u"it_origen_renpy")
        self.it_origen_renpy.setEnabled(True)
        self.it_origen_renpy.setGeometry(QRect(10, 20, 742, 30))
        self.lbl_origen_renpy = QLabel(self.widget_dirs_renpy)
        self.lbl_origen_renpy.setObjectName(u"lbl_origen_renpy")
        self.lbl_origen_renpy.setGeometry(QRect(30, 0, 152, 19))
        self.lbl_destino_renpy = QLabel(self.widget_dirs_renpy)
        self.lbl_destino_renpy.setObjectName(u"lbl_destino_renpy")
        self.lbl_destino_renpy.setGeometry(QRect(30, 60, 152, 19))
        self.it_destino_renpy = QLineEdit(self.widget_dirs_renpy)
        self.it_destino_renpy.setObjectName(u"it_destino_renpy")
        self.it_destino_renpy.setEnabled(True)
        self.it_destino_renpy.setGeometry(QRect(10, 80, 743, 30))
        self.groupBox_dirs_renpy = QGroupBox(self.tab_renpy)
        self.groupBox_dirs_renpy.setObjectName(u"groupBox_dirs_renpy")
        self.groupBox_dirs_renpy.setGeometry(QRect(20, 210, 732, 58))
        self.horizontalLayout_9 = QHBoxLayout(self.groupBox_dirs_renpy)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.rb_dir_unico_renpy = QRadioButton(self.groupBox_dirs_renpy)
        self.rb_dir_unico_renpy.setObjectName(u"rb_dir_unico_renpy")

        self.horizontalLayout_9.addWidget(self.rb_dir_unico_renpy)

        self.rb_dir_multiple_renpy = QRadioButton(self.groupBox_dirs_renpy)
        self.rb_dir_multiple_renpy.setObjectName(u"rb_dir_multiple_renpy")

        self.horizontalLayout_9.addWidget(self.rb_dir_multiple_renpy)

        self.groupBox_tcopia_renpy = QGroupBox(self.tab_renpy)
        self.groupBox_tcopia_renpy.setObjectName(u"groupBox_tcopia_renpy")
        self.groupBox_tcopia_renpy.setGeometry(QRect(20, 390, 732, 58))
        self.horizontalLayout_28 = QHBoxLayout(self.groupBox_tcopia_renpy)
        self.horizontalLayout_28.setObjectName(u"horizontalLayout_28")
        self.rb_tcopia_directa_renpy = QRadioButton(self.groupBox_tcopia_renpy)
        self.rb_tcopia_directa_renpy.setObjectName(u"rb_tcopia_directa_renpy")

        self.horizontalLayout_28.addWidget(self.rb_tcopia_directa_renpy)

        self.rb_tcopia_organizada_renpy = QRadioButton(self.groupBox_tcopia_renpy)
        self.rb_tcopia_organizada_renpy.setObjectName(u"rb_tcopia_organizada_renpy")

        self.horizontalLayout_28.addWidget(self.rb_tcopia_organizada_renpy)

        self.tabWidget.addTab(self.tab_renpy, "")
        self.tab_html = QWidget()
        self.tab_html.setObjectName(u"tab_html")
        self.frame_title_html = QFrame(self.tab_html)
        self.frame_title_html.setObjectName(u"frame_title_html")
        self.frame_title_html.setGeometry(QRect(10, 10, 761, 50))
        sizePolicy.setHeightForWidth(self.frame_title_html.sizePolicy().hasHeightForWidth())
        self.frame_title_html.setSizePolicy(sizePolicy)
        self.frame_title_html.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_title_html.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_12 = QHBoxLayout(self.frame_title_html)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.lbl_title_2 = QLabel(self.frame_title_html)
        self.lbl_title_2.setObjectName(u"lbl_title_2")
        self.lbl_title_2.setFont(font1)
        self.lbl_title_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lbl_title_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_12.addWidget(self.lbl_title_2)

        self.groupBox_dirs_html = QGroupBox(self.tab_html)
        self.groupBox_dirs_html.setObjectName(u"groupBox_dirs_html")
        self.groupBox_dirs_html.setGeometry(QRect(20, 210, 732, 58))
        self.horizontalLayout_10 = QHBoxLayout(self.groupBox_dirs_html)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.rb_dir_unico_html = QRadioButton(self.groupBox_dirs_html)
        self.rb_dir_unico_html.setObjectName(u"rb_dir_unico_html")

        self.horizontalLayout_10.addWidget(self.rb_dir_unico_html)

        self.rb_dir_multiple_html = QRadioButton(self.groupBox_dirs_html)
        self.rb_dir_multiple_html.setObjectName(u"rb_dir_multiple_html")

        self.horizontalLayout_10.addWidget(self.rb_dir_multiple_html)

        self.btn_inicio_html = QPushButton(self.tab_html)
        self.btn_inicio_html.setObjectName(u"btn_inicio_html")
        self.btn_inicio_html.setGeometry(QRect(20, 460, 734, 61))
        self.btn_inicio_html.setFont(font2)
        self.groupBox_actions_html = QGroupBox(self.tab_html)
        self.groupBox_actions_html.setObjectName(u"groupBox_actions_html")
        self.groupBox_actions_html.setGeometry(QRect(20, 280, 732, 100))
        self.gridLayout_2 = QGridLayout(self.groupBox_actions_html)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.chk_img_html = QCheckBox(self.groupBox_actions_html)
        self.chk_img_html.setObjectName(u"chk_img_html")

        self.gridLayout_2.addWidget(self.chk_img_html, 0, 0, 1, 1)

        self.chk_sources_html = QCheckBox(self.groupBox_actions_html)
        self.chk_sources_html.setObjectName(u"chk_sources_html")

        self.gridLayout_2.addWidget(self.chk_sources_html, 0, 1, 1, 1)

        self.chk_all_html = QCheckBox(self.groupBox_actions_html)
        self.chk_all_html.setObjectName(u"chk_all_html")

        self.gridLayout_2.addWidget(self.chk_all_html, 0, 2, 1, 1)

        self.chk_music_html = QCheckBox(self.groupBox_actions_html)
        self.chk_music_html.setObjectName(u"chk_music_html")

        self.gridLayout_2.addWidget(self.chk_music_html, 1, 0, 1, 1)

        self.chk_video_html = QCheckBox(self.groupBox_actions_html)
        self.chk_video_html.setObjectName(u"chk_video_html")

        self.gridLayout_2.addWidget(self.chk_video_html, 1, 1, 1, 1)

        self.widget_dirs_html = QWidget(self.tab_html)
        self.widget_dirs_html.setObjectName(u"widget_dirs_html")
        self.widget_dirs_html.setGeometry(QRect(10, 80, 759, 114))
        self.it_origen_html = QLineEdit(self.widget_dirs_html)
        self.it_origen_html.setObjectName(u"it_origen_html")
        self.it_origen_html.setEnabled(True)
        self.it_origen_html.setGeometry(QRect(10, 20, 742, 30))
        self.lbl_origen_html = QLabel(self.widget_dirs_html)
        self.lbl_origen_html.setObjectName(u"lbl_origen_html")
        self.lbl_origen_html.setGeometry(QRect(30, 0, 152, 19))
        self.lbl_destino_html = QLabel(self.widget_dirs_html)
        self.lbl_destino_html.setObjectName(u"lbl_destino_html")
        self.lbl_destino_html.setGeometry(QRect(30, 60, 152, 19))
        self.it_destino_html = QLineEdit(self.widget_dirs_html)
        self.it_destino_html.setObjectName(u"it_destino_html")
        self.it_destino_html.setEnabled(True)
        self.it_destino_html.setGeometry(QRect(10, 80, 743, 30))
        self.groupBox_tipoCopia_html = QGroupBox(self.tab_html)
        self.groupBox_tipoCopia_html.setObjectName(u"groupBox_tipoCopia_html")
        self.groupBox_tipoCopia_html.setGeometry(QRect(20, 390, 732, 58))
        self.horizontalLayout_29 = QHBoxLayout(self.groupBox_tipoCopia_html)
        self.horizontalLayout_29.setObjectName(u"horizontalLayout_29")
        self.rb_tcopia_directa_html = QRadioButton(self.groupBox_tipoCopia_html)
        self.rb_tcopia_directa_html.setObjectName(u"rb_tcopia_directa_html")

        self.horizontalLayout_29.addWidget(self.rb_tcopia_directa_html)

        self.rb_tcopia_organizada_html = QRadioButton(self.groupBox_tipoCopia_html)
        self.rb_tcopia_organizada_html.setObjectName(u"rb_tcopia_organizada_html")

        self.horizontalLayout_29.addWidget(self.rb_tcopia_organizada_html)

        self.tabWidget.addTab(self.tab_html, "")
        self.tab_rpgm = QWidget()
        self.tab_rpgm.setObjectName(u"tab_rpgm")
        self.frame_title_rpgm = QFrame(self.tab_rpgm)
        self.frame_title_rpgm.setObjectName(u"frame_title_rpgm")
        self.frame_title_rpgm.setGeometry(QRect(10, 10, 761, 50))
        sizePolicy.setHeightForWidth(self.frame_title_rpgm.sizePolicy().hasHeightForWidth())
        self.frame_title_rpgm.setSizePolicy(sizePolicy)
        self.frame_title_rpgm.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_title_rpgm.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_14 = QHBoxLayout(self.frame_title_rpgm)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.lbl_title_3 = QLabel(self.frame_title_rpgm)
        self.lbl_title_3.setObjectName(u"lbl_title_3")
        self.lbl_title_3.setFont(font1)
        self.lbl_title_3.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lbl_title_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_14.addWidget(self.lbl_title_3)

        self.groupBox_dirs_rpgm = QGroupBox(self.tab_rpgm)
        self.groupBox_dirs_rpgm.setObjectName(u"groupBox_dirs_rpgm")
        self.groupBox_dirs_rpgm.setGeometry(QRect(20, 210, 732, 58))
        self.horizontalLayout_19 = QHBoxLayout(self.groupBox_dirs_rpgm)
        self.horizontalLayout_19.setObjectName(u"horizontalLayout_19")
        self.rb_dir_unico_rpgm = QRadioButton(self.groupBox_dirs_rpgm)
        self.rb_dir_unico_rpgm.setObjectName(u"rb_dir_unico_rpgm")

        self.horizontalLayout_19.addWidget(self.rb_dir_unico_rpgm)

        self.rb_dir_multiple_rpgm = QRadioButton(self.groupBox_dirs_rpgm)
        self.rb_dir_multiple_rpgm.setObjectName(u"rb_dir_multiple_rpgm")

        self.horizontalLayout_19.addWidget(self.rb_dir_multiple_rpgm)

        self.btn_inicio_rpgm = QPushButton(self.tab_rpgm)
        self.btn_inicio_rpgm.setObjectName(u"btn_inicio_rpgm")
        self.btn_inicio_rpgm.setGeometry(QRect(20, 460, 734, 61))
        self.btn_inicio_rpgm.setFont(font2)
        self.groupBox_actions_rpgm = QGroupBox(self.tab_rpgm)
        self.groupBox_actions_rpgm.setObjectName(u"groupBox_actions_rpgm")
        self.groupBox_actions_rpgm.setGeometry(QRect(20, 280, 732, 100))
        self.gridLayout_14 = QGridLayout(self.groupBox_actions_rpgm)
        self.gridLayout_14.setObjectName(u"gridLayout_14")
        self.chk_music_rpgm = QCheckBox(self.groupBox_actions_rpgm)
        self.chk_music_rpgm.setObjectName(u"chk_music_rpgm")

        self.gridLayout_14.addWidget(self.chk_music_rpgm, 1, 0, 1, 1)

        self.chk_img_rpgm = QCheckBox(self.groupBox_actions_rpgm)
        self.chk_img_rpgm.setObjectName(u"chk_img_rpgm")

        self.gridLayout_14.addWidget(self.chk_img_rpgm, 0, 0, 1, 1)

        self.chk_sources_rpgm = QCheckBox(self.groupBox_actions_rpgm)
        self.chk_sources_rpgm.setObjectName(u"chk_sources_rpgm")

        self.gridLayout_14.addWidget(self.chk_sources_rpgm, 0, 1, 1, 1)

        self.chk_video_rpgm = QCheckBox(self.groupBox_actions_rpgm)
        self.chk_video_rpgm.setObjectName(u"chk_video_rpgm")

        self.gridLayout_14.addWidget(self.chk_video_rpgm, 1, 1, 1, 1)

        self.chk_all_rpgm = QCheckBox(self.groupBox_actions_rpgm)
        self.chk_all_rpgm.setObjectName(u"chk_all_rpgm")

        self.gridLayout_14.addWidget(self.chk_all_rpgm, 0, 2, 1, 1)

        self.widget_dirs_rpgm = QWidget(self.tab_rpgm)
        self.widget_dirs_rpgm.setObjectName(u"widget_dirs_rpgm")
        self.widget_dirs_rpgm.setGeometry(QRect(10, 80, 759, 114))
        self.it_origen_rpgm = QLineEdit(self.widget_dirs_rpgm)
        self.it_origen_rpgm.setObjectName(u"it_origen_rpgm")
        self.it_origen_rpgm.setEnabled(True)
        self.it_origen_rpgm.setGeometry(QRect(10, 20, 742, 30))
        self.lbl_origen_rpgm = QLabel(self.widget_dirs_rpgm)
        self.lbl_origen_rpgm.setObjectName(u"lbl_origen_rpgm")
        self.lbl_origen_rpgm.setGeometry(QRect(30, 0, 152, 19))
        self.lbl_destino_rpgm = QLabel(self.widget_dirs_rpgm)
        self.lbl_destino_rpgm.setObjectName(u"lbl_destino_rpgm")
        self.lbl_destino_rpgm.setGeometry(QRect(30, 60, 152, 19))
        self.it_destino_rpgm = QLineEdit(self.widget_dirs_rpgm)
        self.it_destino_rpgm.setObjectName(u"it_destino_rpgm")
        self.it_destino_rpgm.setEnabled(True)
        self.it_destino_rpgm.setGeometry(QRect(10, 80, 743, 30))
        self.groupBox_tipoCopia_rpgm = QGroupBox(self.tab_rpgm)
        self.groupBox_tipoCopia_rpgm.setObjectName(u"groupBox_tipoCopia_rpgm")
        self.groupBox_tipoCopia_rpgm.setGeometry(QRect(20, 390, 732, 58))
        self.horizontalLayout_30 = QHBoxLayout(self.groupBox_tipoCopia_rpgm)
        self.horizontalLayout_30.setObjectName(u"horizontalLayout_30")
        self.rb_tcopia_directa_rpgm = QRadioButton(self.groupBox_tipoCopia_rpgm)
        self.rb_tcopia_directa_rpgm.setObjectName(u"rb_tcopia_directa_rpgm")

        self.horizontalLayout_30.addWidget(self.rb_tcopia_directa_rpgm)

        self.rb_tcopia_organizada_rpgm = QRadioButton(self.groupBox_tipoCopia_rpgm)
        self.rb_tcopia_organizada_rpgm.setObjectName(u"rb_tcopia_organizada_rpgm")

        self.horizontalLayout_30.addWidget(self.rb_tcopia_organizada_rpgm)

        self.tabWidget.addTab(self.tab_rpgm, "")
        self.tab_unity = QWidget()
        self.tab_unity.setObjectName(u"tab_unity")
        self.frame_title_unity = QFrame(self.tab_unity)
        self.frame_title_unity.setObjectName(u"frame_title_unity")
        self.frame_title_unity.setGeometry(QRect(10, 10, 761, 50))
        sizePolicy.setHeightForWidth(self.frame_title_unity.sizePolicy().hasHeightForWidth())
        self.frame_title_unity.setSizePolicy(sizePolicy)
        self.frame_title_unity.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_title_unity.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_15 = QHBoxLayout(self.frame_title_unity)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.lbl_title_4 = QLabel(self.frame_title_unity)
        self.lbl_title_4.setObjectName(u"lbl_title_4")
        self.lbl_title_4.setFont(font1)
        self.lbl_title_4.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lbl_title_4.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_15.addWidget(self.lbl_title_4)

        self.groupBox_dirs_unity = QGroupBox(self.tab_unity)
        self.groupBox_dirs_unity.setObjectName(u"groupBox_dirs_unity")
        self.groupBox_dirs_unity.setGeometry(QRect(20, 210, 732, 58))
        self.horizontalLayout_20 = QHBoxLayout(self.groupBox_dirs_unity)
        self.horizontalLayout_20.setObjectName(u"horizontalLayout_20")
        self.rb_dir_unico_unity = QRadioButton(self.groupBox_dirs_unity)
        self.rb_dir_unico_unity.setObjectName(u"rb_dir_unico_unity")

        self.horizontalLayout_20.addWidget(self.rb_dir_unico_unity)

        self.rb_dir_multiple_unity = QRadioButton(self.groupBox_dirs_unity)
        self.rb_dir_multiple_unity.setObjectName(u"rb_dir_multiple_unity")

        self.horizontalLayout_20.addWidget(self.rb_dir_multiple_unity)

        self.btn_inicio_unity = QPushButton(self.tab_unity)
        self.btn_inicio_unity.setObjectName(u"btn_inicio_unity")
        self.btn_inicio_unity.setGeometry(QRect(20, 460, 734, 61))
        self.btn_inicio_unity.setFont(font2)
        self.groupBox_actions_unity = QGroupBox(self.tab_unity)
        self.groupBox_actions_unity.setObjectName(u"groupBox_actions_unity")
        self.groupBox_actions_unity.setGeometry(QRect(20, 280, 732, 100))
        self.gridLayout_4 = QGridLayout(self.groupBox_actions_unity)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.chk_video_unity = QCheckBox(self.groupBox_actions_unity)
        self.chk_video_unity.setObjectName(u"chk_video_unity")

        self.gridLayout_4.addWidget(self.chk_video_unity, 1, 1, 1, 1)

        self.chk_music_unity = QCheckBox(self.groupBox_actions_unity)
        self.chk_music_unity.setObjectName(u"chk_music_unity")

        self.gridLayout_4.addWidget(self.chk_music_unity, 1, 0, 1, 1)

        self.chk_all_unity = QCheckBox(self.groupBox_actions_unity)
        self.chk_all_unity.setObjectName(u"chk_all_unity")

        self.gridLayout_4.addWidget(self.chk_all_unity, 0, 2, 1, 1)

        self.chk_img_unity = QCheckBox(self.groupBox_actions_unity)
        self.chk_img_unity.setObjectName(u"chk_img_unity")

        self.gridLayout_4.addWidget(self.chk_img_unity, 0, 0, 1, 1)

        self.chk_sources_unity = QCheckBox(self.groupBox_actions_unity)
        self.chk_sources_unity.setObjectName(u"chk_sources_unity")

        self.gridLayout_4.addWidget(self.chk_sources_unity, 0, 1, 1, 1)

        self.widget_dirs_unity = QWidget(self.tab_unity)
        self.widget_dirs_unity.setObjectName(u"widget_dirs_unity")
        self.widget_dirs_unity.setGeometry(QRect(10, 80, 759, 114))
        self.it_origen_unity = QLineEdit(self.widget_dirs_unity)
        self.it_origen_unity.setObjectName(u"it_origen_unity")
        self.it_origen_unity.setEnabled(True)
        self.it_origen_unity.setGeometry(QRect(10, 20, 742, 30))
        self.lbl_origen_unity = QLabel(self.widget_dirs_unity)
        self.lbl_origen_unity.setObjectName(u"lbl_origen_unity")
        self.lbl_origen_unity.setGeometry(QRect(30, 0, 152, 19))
        self.lbl_destino_unity = QLabel(self.widget_dirs_unity)
        self.lbl_destino_unity.setObjectName(u"lbl_destino_unity")
        self.lbl_destino_unity.setGeometry(QRect(30, 60, 152, 19))
        self.it_destino_unity = QLineEdit(self.widget_dirs_unity)
        self.it_destino_unity.setObjectName(u"it_destino_unity")
        self.it_destino_unity.setEnabled(True)
        self.it_destino_unity.setGeometry(QRect(10, 80, 743, 30))
        self.groupBox_tipoCopia_unity = QGroupBox(self.tab_unity)
        self.groupBox_tipoCopia_unity.setObjectName(u"groupBox_tipoCopia_unity")
        self.groupBox_tipoCopia_unity.setGeometry(QRect(20, 390, 732, 58))
        self.horizontalLayout_31 = QHBoxLayout(self.groupBox_tipoCopia_unity)
        self.horizontalLayout_31.setObjectName(u"horizontalLayout_31")
        self.rb_tcopia_directa_unity = QRadioButton(self.groupBox_tipoCopia_unity)
        self.rb_tcopia_directa_unity.setObjectName(u"rb_tcopia_directa_unity")

        self.horizontalLayout_31.addWidget(self.rb_tcopia_directa_unity)

        self.rb_tcopia_organizada_unity = QRadioButton(self.groupBox_tipoCopia_unity)
        self.rb_tcopia_organizada_unity.setObjectName(u"rb_tcopia_organizada_unity")

        self.horizontalLayout_31.addWidget(self.rb_tcopia_organizada_unity)

        self.tabWidget.addTab(self.tab_unity, "")
        self.tab_multimedia = QWidget()
        self.tab_multimedia.setObjectName(u"tab_multimedia")
        self.frame_title_multimedia = QFrame(self.tab_multimedia)
        self.frame_title_multimedia.setObjectName(u"frame_title_multimedia")
        self.frame_title_multimedia.setGeometry(QRect(10, 10, 760, 50))
        sizePolicy.setHeightForWidth(self.frame_title_multimedia.sizePolicy().hasHeightForWidth())
        self.frame_title_multimedia.setSizePolicy(sizePolicy)
        self.frame_title_multimedia.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_title_multimedia.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_16 = QHBoxLayout(self.frame_title_multimedia)
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.lbl_title_5 = QLabel(self.frame_title_multimedia)
        self.lbl_title_5.setObjectName(u"lbl_title_5")
        self.lbl_title_5.setFont(font1)
        self.lbl_title_5.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lbl_title_5.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_16.addWidget(self.lbl_title_5)

        self.groupBox_dirs_multimedia = QGroupBox(self.tab_multimedia)
        self.groupBox_dirs_multimedia.setObjectName(u"groupBox_dirs_multimedia")
        self.groupBox_dirs_multimedia.setGeometry(QRect(20, 210, 732, 58))
        self.horizontalLayout_21 = QHBoxLayout(self.groupBox_dirs_multimedia)
        self.horizontalLayout_21.setObjectName(u"horizontalLayout_21")
        self.rb_dir_unico_multimedia = QRadioButton(self.groupBox_dirs_multimedia)
        self.rb_dir_unico_multimedia.setObjectName(u"rb_dir_unico_multimedia")

        self.horizontalLayout_21.addWidget(self.rb_dir_unico_multimedia)

        self.rb_dir_multiple_multimedia = QRadioButton(self.groupBox_dirs_multimedia)
        self.rb_dir_multiple_multimedia.setObjectName(u"rb_dir_multiple_multimedia")

        self.horizontalLayout_21.addWidget(self.rb_dir_multiple_multimedia)

        self.btn_inicio_multimedia = QPushButton(self.tab_multimedia)
        self.btn_inicio_multimedia.setObjectName(u"btn_inicio_multimedia")
        self.btn_inicio_multimedia.setGeometry(QRect(20, 460, 734, 61))
        self.btn_inicio_multimedia.setFont(font2)
        self.groupBox_actions_multimedia = QGroupBox(self.tab_multimedia)
        self.groupBox_actions_multimedia.setObjectName(u"groupBox_actions_multimedia")
        self.groupBox_actions_multimedia.setGeometry(QRect(20, 280, 732, 100))
        self.gridLayout_6 = QGridLayout(self.groupBox_actions_multimedia)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.chk_sources_multimedia = QCheckBox(self.groupBox_actions_multimedia)
        self.chk_sources_multimedia.setObjectName(u"chk_sources_multimedia")

        self.gridLayout_6.addWidget(self.chk_sources_multimedia, 0, 1, 1, 1)

        self.chk_music_multimedia = QCheckBox(self.groupBox_actions_multimedia)
        self.chk_music_multimedia.setObjectName(u"chk_music_multimedia")

        self.gridLayout_6.addWidget(self.chk_music_multimedia, 1, 0, 1, 1)

        self.chk_all_multimedia = QCheckBox(self.groupBox_actions_multimedia)
        self.chk_all_multimedia.setObjectName(u"chk_all_multimedia")

        self.gridLayout_6.addWidget(self.chk_all_multimedia, 0, 2, 1, 1)

        self.chk_img_multimedia = QCheckBox(self.groupBox_actions_multimedia)
        self.chk_img_multimedia.setObjectName(u"chk_img_multimedia")

        self.gridLayout_6.addWidget(self.chk_img_multimedia, 0, 0, 1, 1)

        self.chk_video_multimedia = QCheckBox(self.groupBox_actions_multimedia)
        self.chk_video_multimedia.setObjectName(u"chk_video_multimedia")

        self.gridLayout_6.addWidget(self.chk_video_multimedia, 1, 1, 1, 1)

        self.widget_dirs_multimedia = QWidget(self.tab_multimedia)
        self.widget_dirs_multimedia.setObjectName(u"widget_dirs_multimedia")
        self.widget_dirs_multimedia.setGeometry(QRect(10, 80, 759, 114))
        self.it_origen_multimedia = QLineEdit(self.widget_dirs_multimedia)
        self.it_origen_multimedia.setObjectName(u"it_origen_multimedia")
        self.it_origen_multimedia.setEnabled(True)
        self.it_origen_multimedia.setGeometry(QRect(10, 20, 742, 30))
        self.lbl_origen_multimedia = QLabel(self.widget_dirs_multimedia)
        self.lbl_origen_multimedia.setObjectName(u"lbl_origen_multimedia")
        self.lbl_origen_multimedia.setGeometry(QRect(30, 0, 152, 19))
        self.lbl_destino_multimedia = QLabel(self.widget_dirs_multimedia)
        self.lbl_destino_multimedia.setObjectName(u"lbl_destino_multimedia")
        self.lbl_destino_multimedia.setGeometry(QRect(30, 60, 152, 19))
        self.it_destino_multimedia = QLineEdit(self.widget_dirs_multimedia)
        self.it_destino_multimedia.setObjectName(u"it_destino_multimedia")
        self.it_destino_multimedia.setEnabled(True)
        self.it_destino_multimedia.setGeometry(QRect(10, 80, 743, 30))
        self.groupBox_tipoCopia_multimedia = QGroupBox(self.tab_multimedia)
        self.groupBox_tipoCopia_multimedia.setObjectName(u"groupBox_tipoCopia_multimedia")
        self.groupBox_tipoCopia_multimedia.setGeometry(QRect(20, 390, 732, 58))
        self.horizontalLayout_27 = QHBoxLayout(self.groupBox_tipoCopia_multimedia)
        self.horizontalLayout_27.setObjectName(u"horizontalLayout_27")
        self.rb_tcopia_directa_multimedia = QRadioButton(self.groupBox_tipoCopia_multimedia)
        self.rb_tcopia_directa_multimedia.setObjectName(u"rb_tcopia_directa_multimedia")

        self.horizontalLayout_27.addWidget(self.rb_tcopia_directa_multimedia)

        self.rb_tcopia_organizada_multimedia = QRadioButton(self.groupBox_tipoCopia_multimedia)
        self.rb_tcopia_organizada_multimedia.setObjectName(u"rb_tcopia_organizada_multimedia")

        self.horizontalLayout_27.addWidget(self.rb_tcopia_organizada_multimedia)

        self.tabWidget.addTab(self.tab_multimedia, "")
        self.tab_directorios = QWidget()
        self.tab_directorios.setObjectName(u"tab_directorios")
        self.frame_title_directorios = QFrame(self.tab_directorios)
        self.frame_title_directorios.setObjectName(u"frame_title_directorios")
        self.frame_title_directorios.setGeometry(QRect(10, 10, 761, 50))
        sizePolicy.setHeightForWidth(self.frame_title_directorios.sizePolicy().hasHeightForWidth())
        self.frame_title_directorios.setSizePolicy(sizePolicy)
        self.frame_title_directorios.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_title_directorios.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_17 = QHBoxLayout(self.frame_title_directorios)
        self.horizontalLayout_17.setObjectName(u"horizontalLayout_17")
        self.lbl_title_6 = QLabel(self.frame_title_directorios)
        self.lbl_title_6.setObjectName(u"lbl_title_6")
        self.lbl_title_6.setFont(font1)
        self.lbl_title_6.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lbl_title_6.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_17.addWidget(self.lbl_title_6)

        self.groupBox_actions_directorios = QGroupBox(self.tab_directorios)
        self.groupBox_actions_directorios.setObjectName(u"groupBox_actions_directorios")
        self.groupBox_actions_directorios.setGeometry(QRect(30, 210, 732, 81))
        self.layoutWidget = QWidget(self.groupBox_actions_directorios)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 35, 534, 23))
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.chk_lista_completa_directorios = QCheckBox(self.layoutWidget)
        self.chk_lista_completa_directorios.setObjectName(u"chk_lista_completa_directorios")

        self.horizontalLayout_2.addWidget(self.chk_lista_completa_directorios)

        self.chk_listar_directorios = QCheckBox(self.layoutWidget)
        self.chk_listar_directorios.setObjectName(u"chk_listar_directorios")

        self.horizontalLayout_2.addWidget(self.chk_listar_directorios)

        self.chk_empity_directorios = QCheckBox(self.layoutWidget)
        self.chk_empity_directorios.setObjectName(u"chk_empity_directorios")

        self.horizontalLayout_2.addWidget(self.chk_empity_directorios)

        self.btn_inicio_directorios = QPushButton(self.tab_directorios)
        self.btn_inicio_directorios.setObjectName(u"btn_inicio_directorios")
        self.btn_inicio_directorios.setGeometry(QRect(20, 460, 734, 61))
        self.btn_inicio_directorios.setFont(font2)
        self.widget_dirs_directorios = QWidget(self.tab_directorios)
        self.widget_dirs_directorios.setObjectName(u"widget_dirs_directorios")
        self.widget_dirs_directorios.setGeometry(QRect(10, 80, 759, 114))
        self.it_origen_directorios = QLineEdit(self.widget_dirs_directorios)
        self.it_origen_directorios.setObjectName(u"it_origen_directorios")
        self.it_origen_directorios.setEnabled(True)
        self.it_origen_directorios.setGeometry(QRect(10, 20, 742, 30))
        self.lbl_origen_multimedia_3 = QLabel(self.widget_dirs_directorios)
        self.lbl_origen_multimedia_3.setObjectName(u"lbl_origen_multimedia_3")
        self.lbl_origen_multimedia_3.setGeometry(QRect(30, 0, 152, 19))
        self.lbl_destino_multimedia_3 = QLabel(self.widget_dirs_directorios)
        self.lbl_destino_multimedia_3.setObjectName(u"lbl_destino_multimedia_3")
        self.lbl_destino_multimedia_3.setGeometry(QRect(30, 60, 152, 19))
        self.it_destino_directorios = QLineEdit(self.widget_dirs_directorios)
        self.it_destino_directorios.setObjectName(u"it_destino_directorios")
        self.it_destino_directorios.setEnabled(True)
        self.it_destino_directorios.setGeometry(QRect(10, 80, 743, 30))
        self.tabWidget.addTab(self.tab_directorios, "")
        self.tab_log = QWidget()
        self.tab_log.setObjectName(u"tab_log")
        self.verticalScrollBar = QScrollBar(self.tab_log)
        self.verticalScrollBar.setObjectName(u"verticalScrollBar")
        self.verticalScrollBar.setGeometry(QRect(760, 20, 20, 501))
        self.verticalScrollBar.setOrientation(Qt.Orientation.Vertical)
        self.tabWidget.addTab(self.tab_log, "")
        self.tab_descargas = QWidget()
        self.tab_descargas.setObjectName(u"tab_descargas")
        self.frame_title_descargas = QFrame(self.tab_descargas)
        self.frame_title_descargas.setObjectName(u"frame_title_descargas")
        self.frame_title_descargas.setGeometry(QRect(10, 10, 760, 50))
        sizePolicy.setHeightForWidth(self.frame_title_descargas.sizePolicy().hasHeightForWidth())
        self.frame_title_descargas.setSizePolicy(sizePolicy)
        self.frame_title_descargas.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_title_descargas.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_18 = QHBoxLayout(self.frame_title_descargas)
        self.horizontalLayout_18.setObjectName(u"horizontalLayout_18")
        self.lbl_title_7 = QLabel(self.frame_title_descargas)
        self.lbl_title_7.setObjectName(u"lbl_title_7")
        self.lbl_title_7.setFont(font1)
        self.lbl_title_7.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lbl_title_7.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_18.addWidget(self.lbl_title_7)

        self.btn_inicio_descargas = QPushButton(self.tab_descargas)
        self.btn_inicio_descargas.setObjectName(u"btn_inicio_descargas")
        self.btn_inicio_descargas.setGeometry(QRect(20, 460, 742, 61))
        self.btn_inicio_descargas.setFont(font2)
        self.widget_links_descargas = QWidget(self.tab_descargas)
        self.widget_links_descargas.setObjectName(u"widget_links_descargas")
        self.widget_links_descargas.setGeometry(QRect(10, 130, 759, 322))
        self.lbl_links_descargas = QLabel(self.widget_links_descargas)
        self.lbl_links_descargas.setObjectName(u"lbl_links_descargas")
        self.lbl_links_descargas.setGeometry(QRect(30, 60, 281, 19))
        self.textEdit_descargas = QTextEdit(self.widget_links_descargas)
        self.textEdit_descargas.setObjectName(u"textEdit_descargas")
        self.textEdit_descargas.setGeometry(QRect(10, 80, 741, 236))
        self.lbl_destino_descargas = QLabel(self.widget_links_descargas)
        self.lbl_destino_descargas.setObjectName(u"lbl_destino_descargas")
        self.lbl_destino_descargas.setGeometry(QRect(30, 0, 152, 19))
        self.it_destino_descargas = QLineEdit(self.widget_links_descargas)
        self.it_destino_descargas.setObjectName(u"it_destino_descargas")
        self.it_destino_descargas.setEnabled(True)
        self.it_destino_descargas.setGeometry(QRect(10, 20, 743, 30))
        self.groupBox_tipo_descargas = QGroupBox(self.tab_descargas)
        self.groupBox_tipo_descargas.setObjectName(u"groupBox_tipo_descargas")
        self.groupBox_tipo_descargas.setGeometry(QRect(20, 70, 732, 43))
        self.layoutWidget_2 = QWidget(self.groupBox_tipo_descargas)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(90, 10, 534, 23))
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.rb_yt_descargas = QRadioButton(self.layoutWidget_2)
        self.rb_yt_descargas.setObjectName(u"rb_yt_descargas")

        self.horizontalLayout_3.addWidget(self.rb_yt_descargas)

        self.rb_img_descargas = QRadioButton(self.layoutWidget_2)
        self.rb_img_descargas.setObjectName(u"rb_img_descargas")

        self.horizontalLayout_3.addWidget(self.rb_img_descargas)

        self.tabWidget.addTab(self.tab_descargas, "")
        self.frame_resultados = QFrame(self.centralwidget)
        self.frame_resultados.setObjectName(u"frame_resultados")
        self.frame_resultados.setGeometry(QRect(10, 580, 781, 80))
        self.frame_resultados.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_resultados.setFrameShadow(QFrame.Shadow.Raised)
        self.progressBar = QProgressBar(self.frame_resultados)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(20, 40, 731, 23))
        self.progressBar.setFont(font)
        self.progressBar.setValue(0)
        self.statusLabel = QLabel(self.frame_resultados)
        self.statusLabel.setObjectName(u"statusLabel")
        self.statusLabel.setGeometry(QRect(20, 10, 71, 16))
        self.statusLabel.setFont(font)
        self.statusTextLabel = QLabel(self.frame_resultados)
        self.statusTextLabel.setObjectName(u"statusTextLabel")
        self.statusTextLabel.setGeometry(QRect(180, 10, 581, 16))
        self.statusTextLabel.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_inicio), QCoreApplication.translate("MainWindow", u"Inicio", None))
        self.lbl_title.setText(QCoreApplication.translate("MainWindow", u"Juegos Renpy", None))
        self.groupBox_actions_renpy.setTitle(QCoreApplication.translate("MainWindow", u"Acciones", None))
        self.chk_rpa_renpy.setText(QCoreApplication.translate("MainWindow", u"Extraer RPA", None))
        self.chk_sources_renpy.setText(QCoreApplication.translate("MainWindow", u"Copiar Fuentes", None))
        self.chk_music_renpy.setText(QCoreApplication.translate("MainWindow", u"Copiar M\u00fasica", None))
        self.chk_all_renpy.setText(QCoreApplication.translate("MainWindow", u"Copiar Todo", None))
        self.chk_rpyc_renpy.setText(QCoreApplication.translate("MainWindow", u"Descompilar RPYC", None))
        self.chk_video_renpy.setText(QCoreApplication.translate("MainWindow", u"Copiar Videos", None))
        self.chk_img_renpy.setText(QCoreApplication.translate("MainWindow", u"Copiar Imagenes", None))
        self.btn_inicio_renpy.setText(QCoreApplication.translate("MainWindow", u"Iniciar", None))
        self.lbl_origen_renpy.setText(QCoreApplication.translate("MainWindow", u"Directorio Origen:", None))
        self.lbl_destino_renpy.setText(QCoreApplication.translate("MainWindow", u"Directorio Destino:", None))
        self.groupBox_dirs_renpy.setTitle(QCoreApplication.translate("MainWindow", u"Tipo Directorio", None))
        self.rb_dir_unico_renpy.setText(QCoreApplication.translate("MainWindow", u"Directorio Unico", None))
        self.rb_dir_multiple_renpy.setText(QCoreApplication.translate("MainWindow", u"Directorio Multiple", None))
        self.groupBox_tcopia_renpy.setTitle(QCoreApplication.translate("MainWindow", u"Tipo Copia", None))
        self.rb_tcopia_directa_renpy.setText(QCoreApplication.translate("MainWindow", u"Directa", None))
        self.rb_tcopia_organizada_renpy.setText(QCoreApplication.translate("MainWindow", u"Organizada", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_renpy), QCoreApplication.translate("MainWindow", u"Ren'py", None))
        self.lbl_title_2.setText(QCoreApplication.translate("MainWindow", u"Juegos HTML", None))
        self.groupBox_dirs_html.setTitle(QCoreApplication.translate("MainWindow", u"Tipo Directorio", None))
        self.rb_dir_unico_html.setText(QCoreApplication.translate("MainWindow", u"Directorio Unico", None))
        self.rb_dir_multiple_html.setText(QCoreApplication.translate("MainWindow", u"Directorio Multiple", None))
        self.btn_inicio_html.setText(QCoreApplication.translate("MainWindow", u"Iniciar", None))
        self.groupBox_actions_html.setTitle(QCoreApplication.translate("MainWindow", u"Acciones", None))
        self.chk_img_html.setText(QCoreApplication.translate("MainWindow", u"Copiar Imagenes", None))
        self.chk_sources_html.setText(QCoreApplication.translate("MainWindow", u"Copiar Fuentes", None))
        self.chk_all_html.setText(QCoreApplication.translate("MainWindow", u"Copiar Todo", None))
        self.chk_music_html.setText(QCoreApplication.translate("MainWindow", u"Copiar M\u00fasica", None))
        self.chk_video_html.setText(QCoreApplication.translate("MainWindow", u"Copiar Videos", None))
        self.lbl_origen_html.setText(QCoreApplication.translate("MainWindow", u"Directorio Origen:", None))
        self.lbl_destino_html.setText(QCoreApplication.translate("MainWindow", u"Directorio Destino:", None))
        self.groupBox_tipoCopia_html.setTitle(QCoreApplication.translate("MainWindow", u"Tipo Copia", None))
        self.rb_tcopia_directa_html.setText(QCoreApplication.translate("MainWindow", u"Directa", None))
        self.rb_tcopia_organizada_html.setText(QCoreApplication.translate("MainWindow", u"Organizada", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_html), QCoreApplication.translate("MainWindow", u"HTML", None))
        self.lbl_title_3.setText(QCoreApplication.translate("MainWindow", u"Juegos RPGM", None))
        self.groupBox_dirs_rpgm.setTitle(QCoreApplication.translate("MainWindow", u"Tipo Directorio", None))
        self.rb_dir_unico_rpgm.setText(QCoreApplication.translate("MainWindow", u"Directorio Unico", None))
        self.rb_dir_multiple_rpgm.setText(QCoreApplication.translate("MainWindow", u"Directorio Multiple", None))
        self.btn_inicio_rpgm.setText(QCoreApplication.translate("MainWindow", u"Iniciar", None))
        self.groupBox_actions_rpgm.setTitle(QCoreApplication.translate("MainWindow", u"Acciones", None))
        self.chk_music_rpgm.setText(QCoreApplication.translate("MainWindow", u"Copiar M\u00fasica", None))
        self.chk_img_rpgm.setText(QCoreApplication.translate("MainWindow", u"Copiar Imagenes", None))
        self.chk_sources_rpgm.setText(QCoreApplication.translate("MainWindow", u"Copiar Fuentes", None))
        self.chk_video_rpgm.setText(QCoreApplication.translate("MainWindow", u"Copiar Videos", None))
        self.chk_all_rpgm.setText(QCoreApplication.translate("MainWindow", u"Copiar Todo", None))
        self.lbl_origen_rpgm.setText(QCoreApplication.translate("MainWindow", u"Directorio Origen:", None))
        self.lbl_destino_rpgm.setText(QCoreApplication.translate("MainWindow", u"Directorio Destino:", None))
        self.groupBox_tipoCopia_rpgm.setTitle(QCoreApplication.translate("MainWindow", u"Tipo Copia", None))
        self.rb_tcopia_directa_rpgm.setText(QCoreApplication.translate("MainWindow", u"Directa", None))
        self.rb_tcopia_organizada_rpgm.setText(QCoreApplication.translate("MainWindow", u"Organizada", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rpgm), QCoreApplication.translate("MainWindow", u"RPGM", None))
        self.lbl_title_4.setText(QCoreApplication.translate("MainWindow", u"Juegos Unity", None))
        self.groupBox_dirs_unity.setTitle(QCoreApplication.translate("MainWindow", u"Tipo Directorio", None))
        self.rb_dir_unico_unity.setText(QCoreApplication.translate("MainWindow", u"Directorio Unico", None))
        self.rb_dir_multiple_unity.setText(QCoreApplication.translate("MainWindow", u"Directorio Multiple", None))
        self.btn_inicio_unity.setText(QCoreApplication.translate("MainWindow", u"Iniciar", None))
        self.groupBox_actions_unity.setTitle(QCoreApplication.translate("MainWindow", u"Acciones", None))
        self.chk_video_unity.setText(QCoreApplication.translate("MainWindow", u"Copiar Videos", None))
        self.chk_music_unity.setText(QCoreApplication.translate("MainWindow", u"Copiar M\u00fasica", None))
        self.chk_all_unity.setText(QCoreApplication.translate("MainWindow", u"Copiar Todo", None))
        self.chk_img_unity.setText(QCoreApplication.translate("MainWindow", u"Copiar Imagenes", None))
        self.chk_sources_unity.setText(QCoreApplication.translate("MainWindow", u"Copiar Fuentes", None))
        self.lbl_origen_unity.setText(QCoreApplication.translate("MainWindow", u"Directorio Origen:", None))
        self.lbl_destino_unity.setText(QCoreApplication.translate("MainWindow", u"Directorio Destino:", None))
        self.groupBox_tipoCopia_unity.setTitle(QCoreApplication.translate("MainWindow", u"Tipo Copia", None))
        self.rb_tcopia_directa_unity.setText(QCoreApplication.translate("MainWindow", u"Directa", None))
        self.rb_tcopia_organizada_unity.setText(QCoreApplication.translate("MainWindow", u"Organizada", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_unity), QCoreApplication.translate("MainWindow", u"Unity", None))
        self.lbl_title_5.setText(QCoreApplication.translate("MainWindow", u"Multimedia", None))
        self.groupBox_dirs_multimedia.setTitle(QCoreApplication.translate("MainWindow", u"Tipo Directorio", None))
        self.rb_dir_unico_multimedia.setText(QCoreApplication.translate("MainWindow", u"Directorio Unico", None))
        self.rb_dir_multiple_multimedia.setText(QCoreApplication.translate("MainWindow", u"Directorio Multiple", None))
        self.btn_inicio_multimedia.setText(QCoreApplication.translate("MainWindow", u"Iniciar", None))
        self.groupBox_actions_multimedia.setTitle(QCoreApplication.translate("MainWindow", u"Acciones", None))
        self.chk_sources_multimedia.setText(QCoreApplication.translate("MainWindow", u"Copiar Fuentes", None))
        self.chk_music_multimedia.setText(QCoreApplication.translate("MainWindow", u"Copiar M\u00fasica", None))
        self.chk_all_multimedia.setText(QCoreApplication.translate("MainWindow", u"Copiar Todo", None))
        self.chk_img_multimedia.setText(QCoreApplication.translate("MainWindow", u"Copiar Imagenes", None))
        self.chk_video_multimedia.setText(QCoreApplication.translate("MainWindow", u"Copiar Videos", None))
        self.lbl_origen_multimedia.setText(QCoreApplication.translate("MainWindow", u"Directorio Origen:", None))
        self.lbl_destino_multimedia.setText(QCoreApplication.translate("MainWindow", u"Directorio Destino:", None))
        self.groupBox_tipoCopia_multimedia.setTitle(QCoreApplication.translate("MainWindow", u"Tipo Copia", None))
        self.rb_tcopia_directa_multimedia.setText(QCoreApplication.translate("MainWindow", u"Directa", None))
        self.rb_tcopia_organizada_multimedia.setText(QCoreApplication.translate("MainWindow", u"Organizada", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_multimedia), QCoreApplication.translate("MainWindow", u"Multimedia", None))
        self.lbl_title_6.setText(QCoreApplication.translate("MainWindow", u"Directorios", None))
        self.groupBox_actions_directorios.setTitle(QCoreApplication.translate("MainWindow", u"Acciones", None))
        self.chk_lista_completa_directorios.setText(QCoreApplication.translate("MainWindow", u"Listar Contenido", None))
        self.chk_listar_directorios.setText(QCoreApplication.translate("MainWindow", u"Listar Sub Directorios", None))
        self.chk_empity_directorios.setText(QCoreApplication.translate("MainWindow", u"Eliminar Carpetas vacias", None))
        self.btn_inicio_directorios.setText(QCoreApplication.translate("MainWindow", u"Iniciar", None))
        self.lbl_origen_multimedia_3.setText(QCoreApplication.translate("MainWindow", u"Directorio Origen:", None))
        self.lbl_destino_multimedia_3.setText(QCoreApplication.translate("MainWindow", u"Directorio Destino:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_directorios), QCoreApplication.translate("MainWindow", u"Directorios", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_log), QCoreApplication.translate("MainWindow", u"Log", None))
        self.lbl_title_7.setText(QCoreApplication.translate("MainWindow", u"Descargas", None))
        self.btn_inicio_descargas.setText(QCoreApplication.translate("MainWindow", u"Descargar", None))
        self.lbl_links_descargas.setText(QCoreApplication.translate("MainWindow", u"Pega aqu\u00ed los enlaces (uno por l\u00ednea)", None))
        self.lbl_destino_descargas.setText(QCoreApplication.translate("MainWindow", u"Directorio Destino:", None))
        self.groupBox_tipo_descargas.setTitle("")
        self.rb_yt_descargas.setText(QCoreApplication.translate("MainWindow", u"Youtube", None))
        self.rb_img_descargas.setText(QCoreApplication.translate("MainWindow", u"Imagenes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_descargas), QCoreApplication.translate("MainWindow", u"Descargas", None))
        self.statusLabel.setText(QCoreApplication.translate("MainWindow", u"Estado:", None))
        self.statusTextLabel.setText("")
    # retranslateUi

